version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/react-src/node_modules
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fileupload
      - MASTER_ENCRYPTION_KEY=${MASTER_ENCRYPTION_KEY:-generate}
    depends_on:
      - db
    restart: unless-stopped
    # Wait for db to be ready and start Flask in debug mode
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to start...'
        sleep 5
        touch app.py
        export FLASK_APP=app.py
        export FLASK_DEBUG=1
        python -m flask run --host=0.0.0.0 --port=5000
      "

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fileupload
    restart: unless-stopped
    ports:
      - "5432:5432"
    # Initialize the database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
